// Auto-generated by scripts/embed-font.cjs — do not edit by hand.
// This stub gets replaced by the real base64-encoded TTF data at
// install / build time. Empty strings here trigger the Helvetica
// fallback in invoice.ts.
export const ROBOTO_REGULAR_B64 = '';
export const ROBOTO_BOLD_B64 = '';
