#!/usr/bin/env node
/**
 * Read the Roboto TTF files from node_modules/roboto-fontface and
 * write them as base64 string exports into lib/roboto-embedded.ts.
 *
 * Runs in postinstall + build so the embedded file is fresh on
 * every install/deploy. Embedding the binary into the JS bundle is
 * what guarantees the fonts ship with the Vercel serverless function
 * — outputFileTracingIncludes wasn't reliably picking them up.
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const REGULAR_PATH = path.join(ROOT, 'node_modules/roboto-fontface/fonts/Roboto/Roboto-Regular.ttf');
const BOLD_PATH = path.join(ROOT, 'node_modules/roboto-fontface/fonts/Roboto/Roboto-Bold.ttf');
const OUT_PATH = path.join(ROOT, 'lib/roboto-embedded.ts');

function tryRead(p) {
  try {
    return fs.readFileSync(p);
  } catch (e) {
    return null;
  }
}

const regular = tryRead(REGULAR_PATH);
const bold = tryRead(BOLD_PATH);

if (!regular || !bold) {
  // Don't break the build if roboto-fontface isn't installed (e.g. on
  // a CI step that runs before npm install). Emit empty strings — the
  // invoice renderer falls back to Helvetica when the buffers are empty.
  console.warn('[embed-font] roboto-fontface TTFs not found, writing empty stubs');
  fs.writeFileSync(
    OUT_PATH,
    `// Auto-generated by scripts/embed-font.cjs — do not edit by hand.\n` +
      `export const ROBOTO_REGULAR_B64 = '';\n` +
      `export const ROBOTO_BOLD_B64 = '';\n`,
  );
  process.exit(0);
}

const content =
  `// Auto-generated by scripts/embed-font.cjs — do not edit by hand.\n` +
  `// Roboto Regular + Bold TTFs embedded as base64 so they ship inside\n` +
  `// the Vercel serverless function bundle (file-trace based bundling\n` +
  `// was unreliable for these binary assets).\n` +
  `export const ROBOTO_REGULAR_B64 = ${JSON.stringify(regular.toString('base64'))};\n` +
  `export const ROBOTO_BOLD_B64 = ${JSON.stringify(bold.toString('base64'))};\n`;

fs.writeFileSync(OUT_PATH, content);
console.log(
  `[embed-font] wrote ${OUT_PATH} (regular: ${regular.length} bytes, bold: ${bold.length} bytes)`,
);
