#!/usr/bin/env node
/**
 * Read the Roboto TTF files from assets/fonts/ and write them as
 * base64 string exports into lib/roboto-embedded.ts.
 *
 * Roboto TTFs are committed directly in this repo (Apache 2.0,
 * sourced from googlefonts/roboto) rather than pulled from an npm
 * package — past attempts via roboto-fontface and @fontsource/roboto
 * both failed because neither ships TTF files (woff/woff2 only, which
 * PDFKit cannot read), causing the embed script to silently write
 * empty stubs and the invoice to fall back to Helvetica (no ₹ glyph).
 *
 * Runs in postinstall + build so the embedded file is regenerated on
 * every install/deploy. Embedding the binary as base64 inside the JS
 * bundle is what guarantees the fonts ship with the Vercel serverless
 * function — outputFileTracingIncludes wasn't reliably picking them up.
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const REGULAR_PATH = path.join(ROOT, 'assets/fonts/Roboto-Regular.ttf');
const BOLD_PATH = path.join(ROOT, 'assets/fonts/Roboto-Bold.ttf');
const OUT_PATH = path.join(ROOT, 'lib/roboto-embedded.ts');

function tryRead(p) {
  try {
    return fs.readFileSync(p);
  } catch (e) {
    return null;
  }
}

const regular = tryRead(REGULAR_PATH);
const bold = tryRead(BOLD_PATH);

if (!regular || !bold) {
  // The TTFs are committed in the repo so this should never happen
  // in a normal install. Fail loudly instead of silently writing an
  // empty stub — silently falling back to Helvetica is exactly the
  // bug that caused the ₹ glyph to render as superscript-1 in
  // production for weeks.
  console.error(
    '[embed-font] FATAL: TTFs missing from assets/fonts/. ' +
      'Expected Roboto-Regular.ttf and Roboto-Bold.ttf at:\n' +
      `  ${REGULAR_PATH}\n  ${BOLD_PATH}`,
  );
  process.exit(1);
}

const content =
  `// Auto-generated by scripts/embed-font.cjs — do not edit by hand.\n` +
  `// Roboto Regular + Bold TTFs embedded as base64 so they ship inside\n` +
  `// the Vercel serverless function bundle (file-trace based bundling\n` +
  `// was unreliable for these binary assets).\n` +
  `export const ROBOTO_REGULAR_B64 = ${JSON.stringify(regular.toString('base64'))};\n` +
  `export const ROBOTO_BOLD_B64 = ${JSON.stringify(bold.toString('base64'))};\n`;

fs.writeFileSync(OUT_PATH, content);
console.log(
  `[embed-font] wrote ${OUT_PATH} (regular: ${regular.length} bytes, bold: ${bold.length} bytes)`,
);
