#!/usr/bin/env node
/**
 * Read assets/stamp.png (the company seal) and write it as a base64
 * export into lib/stamp-embedded.ts, so the stamp ships INSIDE the
 * Vercel serverless bundle — same reasoning as embed-font.cjs (file
 * paths aren't reliably traced into the function).
 *
 * Unlike the fonts, the stamp is OPTIONAL: if assets/stamp.png is
 * missing we write an empty stub and the invoice simply renders
 * without a stamp (NO build failure). Drop a stamp.png in and the
 * next build/postinstall picks it up automatically.
 *
 * Runs in postinstall + build alongside embed-font.cjs.
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const STAMP_PATH = path.join(ROOT, 'assets/stamp.png');
const OUT_PATH = path.join(ROOT, 'lib/stamp-embedded.ts');

let b64 = '';
try {
  b64 = fs.readFileSync(STAMP_PATH).toString('base64');
} catch {
  console.warn('[embed-stamp] assets/stamp.png not found — invoices will render without a stamp');
}

const content =
  `// AUTO-GENERATED by scripts/embed-stamp.cjs — do not edit by hand.\n` +
  `// Base64 of assets/stamp.png, embedded so the company seal ships in\n` +
  `// the Vercel serverless bundle. Empty string = no stamp (optional).\n` +
  `export const STAMP_PNG_B64 = ${JSON.stringify(b64)};\n`;

fs.writeFileSync(OUT_PATH, content);
console.log(
  `[embed-stamp] wrote ${OUT_PATH} (${b64 ? Math.round(b64.length * 0.75) + ' bytes' : 'EMPTY — no stamp yet'})`,
);
